kind: ConfigMap
apiVersion: v1
metadata:
  name: k8s.http
  namespace: f5demo
  labels:
    f5type: virtual-server
data:
  # See the f5-schema table for schema-controller compatibility
  # https://clouddocs.f5.com/containers/latest/releases_and_versioning.html#f5-schema
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json" #change this
  data: |
    {
      "virtualServer": {
        "backend": {
          "serviceName": "f5-hello-world",
          "servicePort": 80
        },
        "frontend": {
          "partition": "k8s",
          "iapp": "/Common/f5.http",
          "iappPoolMemberTable": {
            "name": "pool__members",
            "columns": [
                {"name": "addr", "kind": "IPAddress"},
                {"name": "port", "kind": "Port"},
                {"name": "connection_limit", "value": "0"}
            ]
          },
          "iappOptions": {
            "description": "appsvc iApp"
          },
          "iappVariables": {
            "iapp_strictUpdates":"disabled",
            "pool_mask":"255.255.255.255",
            "iapp_appStats":"enabled",
            "iapp_mode":"auto",
            "iapp_logLevel":"9",
            "iapp_routeDomain":"auto",
            "iapp_asmDeployMode":"preserve-bypass",
            "iapp_asmDeployMode":"preserve-bypass",
            "pool__DefaultPoolIndex": "0",
            "pool__MemberDefaultPort": 8080,
            "vs__RouteAdv":"disabled",
            "vs__SourceAddress":"0.0.0.0/0",
            "vs__ipProtocol":"tcp",
            "vs__ConnectionLimit:"0",
            "vs__ProfileClientProtocol":"/Common/tcp-wan-optimized",
            "vs__ProfileServerProtocol":"/Common/tcp-lan-optimized",
            "vs__SNATConfig":"automap",
            "vs__ProfileSecurityIPBlacklist":"none",
            "vs__OptionSourcePort":"preserve",
            "vs__OptionConnectionMirroring":"disabled",
            "l7policy__strategy":"/Common/first-match",
            "l7policy__defaultASM":"bypass",
            "l7policy__defaultL7DOS":"bypass",
            "feature__statsTLS":"auto",
            "feature__statsHTTP":"auto",
            "feature__insertXForwarderFor":"auto",
            "feature__redirectToHTTPS":"auto",
            "feature__sslEastCipher":"disabled",
            "feature__securityEnableHSTS":"disabled",
            "feature__easyL4Firewall":"disabled",
            "vs__IpProtocol":"tcp",
            "vs__SNATConfig":"automap",
            "vs__ProfileHTTP":"/Common/http",
            "vs__ProfileOneConnect":"/Common/oneconnect",
            "vs__ProfileCompression":"/Common/httpcompression",
            "vs__ProfileDefaultPersist":"/Common/cookie",
            "vs__ProfileFallbackPersist":"/Common/source_addr",
            "vs__ProfileClientSSLCert":"",
            "vs__ProfileClientSSLKey":"",
            "vs__ProfileClientSSLCipherString":"DEFAULT",
            "vs__ProfileClientSSLadvOptions":"handshake-timeout=60;strict-resume=enabled",
            "pool_addr":"1.1.1.1",
            "pool_pool_to_use": "/#create_new#",
            "pool_port": "443"
          }
        }
      }
    }
